project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: "images/logo/STAC-Logo-White.png"
    left:
      - sidebar:CBS
      - href: Engaging Educational Partners.qmd
        text: "Engaging Educational Partners"      
      - href: WCFSI.qmd
        text: "Whole-Child & Family Supports"
      - href: Goals and Actions.qmd
        text: "Goals & Actions"
      - href: reflections.qmd
        text: "Reflections"    
      - href: system-level-analysis.qmd
        text: "LEA-Level Analysis"

  sidebar:
    - id: CBS
      title: "Capacity Building Strategies"
      style: "floating"
      collapse-level: 2
      contents: 
        - href: CBS/Schools - Capacity Building Strategies.qmd
          text: "School"  
        - href: CBS/cbs-lea.qmd
          text: "LEA"
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

